### ISSUE TITLE
AttributeError: 'WyzePlugin' object has no attribute 'wyze'

### ISSUE THREAD

**Issue by tylerburleigh** [eshapiro42/OctoPrint-Wyze#15]
**Check your Python version**
```
OctoPrint 1.9.3
Python 3.9.2 
OctoPi* 1.0.0 (build 2023.10.09.151442)
```

**Describe the bug**
I've installed the plugin, I've entered my Wyze credentials, but I don't see any Wyze devices in the plugin section.

When I check the `octoprint.log` file, I see this error, which may be related:

```
2023-12-15 17:59:43,323 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin wyze
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/server/api/__init__.py", line 159, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_wyze/__init__.py", line 149, in on_api_command
    devices = self.wyze.get_devices(self.event_handler)
AttributeError: 'WyzePlugin' object has no attribute 'wyze'
```

**To Reproduce**
1. Install plugin
2. Enter credentials
3. Check `octoprint.log` file

**Desktop (please complete the following information):**
 - OS: Ubuntu 23
 - Browser: Firefox
 - Version: 118

**Comment by tylerburleigh** [comment]
Nevermind, I was looking in the wrong place for devices. It seems this error is immaterial, the connection is working.
